/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import model.user;


/**
 *
 * @author Jeel
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel bottompanel;
    public FormPanel(JPanel inputpanel) {
        initComponents();
        this.bottompanel = inputpanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_title = new javax.swing.JLabel();
        lbl_fname = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_message = new javax.swing.JLabel();
        lbl_patienttype = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        btn_image = new javax.swing.JButton();
        txt_date = new com.toedter.calendar.JDateChooser();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_message = new javax.swing.JTextArea();
        dtype = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        lbl_path = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        error_fname = new javax.swing.JLabel();
        error_lname = new javax.swing.JLabel();
        error_age = new javax.swing.JLabel();
        error_email = new javax.swing.JLabel();
        error_message = new javax.swing.JLabel();
        error_ptype = new javax.swing.JLabel();
        error_gender = new javax.swing.JLabel();

        lbl_title.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lbl_title.setText("Patient Registration Form");

        lbl_fname.setText("First Name:");

        lbl_lastname.setText("Last Name:");

        lbl_age.setText("Age");

        lbl_email.setText("Email");

        lbl_message.setText("Message");

        lbl_patienttype.setText("Patient Type");

        lbl_gender.setText("Gender");

        btn_image.setText("Image");
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });

        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fnameKeyReleased(evt);
            }
        });

        txt_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lnameKeyReleased(evt);
            }
        });

        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ageKeyReleased(evt);
            }
        });

        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });

        txta_message.setColumns(20);
        txta_message.setRows(5);
        txta_message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txta_messageKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txta_message);

        dtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New patient", "old Patient" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        lbl_path.setForeground(new java.awt.Color(0, 255, 0));

        jLabel1.setText("Date");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        error_fname.setForeground(new java.awt.Color(255, 0, 0));

        error_lname.setForeground(new java.awt.Color(255, 0, 0));

        error_age.setForeground(new java.awt.Color(255, 0, 0));

        error_email.setForeground(new java.awt.Color(255, 0, 0));

        error_message.setForeground(new java.awt.Color(255, 0, 0));

        error_ptype.setForeground(new java.awt.Color(255, 0, 0));

        error_gender.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbl_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_gender)
                            .addComponent(btn_image)
                            .addComponent(lbl_patienttype)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_fname)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_age)
                                    .addComponent(lbl_lastname)
                                    .addComponent(lbl_email)
                                    .addComponent(lbl_message)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(error_ptype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(dtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_email)
                            .addComponent(txt_age)
                            .addComponent(txt_lname)
                            .addComponent(txt_fname)
                            .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(error_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2)))
                                .addGap(55, 55, 55))
                            .addComponent(lbl_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fname)
                            .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(error_fname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_lastname)
                            .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(error_lname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_age)
                            .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_email)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_email)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_message)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_patienttype)
                            .addComponent(dtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_ptype)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_gender)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error_gender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_path, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_submit)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        user newuser = new user();
        
        newuser.setFname(txt_fname.getText());
        newuser.setLname(txt_lname.getText());
        newuser.setAge(txt_age.getText());
        newuser.setEmail(txt_email.getText());
        newuser.setMessage(txta_message.getText());
        newuser.setEmail(txt_email.getText());
        newuser.setDate(txt_date.getDate().toString());
        newuser.setGender(buttonGroup1.getSelection().getActionCommand());
        newuser.setType(dtype.getSelectedItem().toString());
        newuser.setFilename(filename);
        //System.out.println(" " + fname +" "+ lname +" "+ age +" "+ email +" "+ message);

        
        viewpanel newviewpanel = new viewpanel(newuser);
        bottompanel.add(newviewpanel);
        CardLayout layout = (CardLayout) bottompanel.getLayout();
        layout.next(bottompanel);
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{2,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_fname.getText());
        if(!match.matches()){
            error_fname.setText("Please enter Only Alphabets in first name");
        }
        else {
            error_fname.setText(null);
        }
    }//GEN-LAST:event_txt_fnameKeyReleased

    private void txt_lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{2,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_lname.getText());
        if(!match.matches()){
            error_lname.setText("Please enter Only Alphabet in last name");
        }
        else {
            error_lname.setText(null);
        }
    }//GEN-LAST:event_txt_lnameKeyReleased

    private void txt_ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,110}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_age.getText());
        if(!match.matches()){
            error_age.setText("Please enter only number, no invalid characters allowed");
        }
        else {
            error_age.setText(null);
        }
    }//GEN-LAST:event_txt_ageKeyReleased

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}@[a-zA-Z]{0,10}.[a-zA-Z]{0,3}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_email.getText());
        if(!match.matches()){
            error_email.setText("Please enter a valid Email address (for e.g; abc@gmail.com)");
        }
        else {
            error_email.setText(null);
        }
    }//GEN-LAST:event_txt_emailKeyReleased

    private void txta_messageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta_messageKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 ]{20,100}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txta_message.getText());
        if(!match.matches()){
            error_message.setText("Please describe your message, write atleast 20 characters");
        }
        else {
            error_message.setText(null);
        }
    }//GEN-LAST:event_txta_messageKeyReleased

    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        lbl_path.setText(filename);
//        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(filename);
    }//GEN-LAST:event_btn_imageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_image;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dtype;
    private javax.swing.JLabel error_age;
    private javax.swing.JLabel error_email;
    private javax.swing.JLabel error_fname;
    private javax.swing.JLabel error_gender;
    private javax.swing.JLabel error_lname;
    private javax.swing.JLabel error_message;
    private javax.swing.JLabel error_ptype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_path;
    private javax.swing.JLabel lbl_patienttype;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_age;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextArea txta_message;
    // End of variables declaration//GEN-END:variables
        String filename;

}
